SELECT AUDITORIUM_TYPE, SUM(AUDITORIUM_CAPACITY) AS SUM_CAP , AVG(AUDITORIUM_CAPACITY) AS AV_CAP,
MAX(AUDITORIUM_CAPACITY) AS MAX_CAP, MIN(AUDITORIUM_CAPACITY) AS Min_CAP
FROM AUDITORIUM
GROUP BY AUDITORIUM_TYPE
HAVING  MIN(AUDITORIUM_CAPACITY) >20