USE [master]
GO

/****** Object:  Database [DbIskhakov]    Script Date: 25.10.2023 9:28:09 ******/
CREATE DATABASE [DbIskhakov]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DbIskhakov', FILENAME = N'D:\Program File\MSSQL15.SQLEXPRESS\MSSQL\DATA\DbIskhakov.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [G1] 
( NAME = N'G1', FILENAME = N'D:\Program File\MSSQL15.SQLEXPRESS\MSSQL\DATA\G1.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [G2] 
( NAME = N'G2-1', FILENAME = N'D:\Program File\MSSQL15.SQLEXPRESS\MSSQL\DATA\G2-1.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ),
( NAME = N'G2-2', FILENAME = N'D:\Program File\MSSQL15.SQLEXPRESS\MSSQL\DATA\G2-2.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [G3] 
( NAME = N'G3-1', FILENAME = N'D:\Program File\MSSQL15.SQLEXPRESS\MSSQL\DATA\G3-1.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ),
( NAME = N'G3-2', FILENAME = N'D:\Program File\MSSQL15.SQLEXPRESS\MSSQL\DATA\G3-2.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ),
( NAME = N'G3-3', FILENAME = N'D:\Program File\MSSQL15.SQLEXPRESS\MSSQL\DATA\G3-3.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DbIskhakov_log', FILENAME = N'D:\Program File\MSSQL15.SQLEXPRESS\MSSQL\DATA\DbIskhakov_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DbIskhakov].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DbIskhakov] SET ANSI_NULL_DEFAULT OFF --будем что-то мен€ть--
GO

ALTER DATABASE [DbIskhakov] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DbIskhakov] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DbIskhakov] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DbIskhakov] SET ARITHABORT OFF 
GO

ALTER DATABASE [DbIskhakov] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DbIskhakov] SET AUTO_SHRINK OFF --сжатие--
GO

ALTER DATABASE [DbIskhakov] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DbIskhakov] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DbIskhakov] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DbIskhakov] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DbIskhakov] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DbIskhakov] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DbIskhakov] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DbIskhakov] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DbIskhakov] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DbIskhakov] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DbIskhakov] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DbIskhakov] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DbIskhakov] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DbIskhakov] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DbIskhakov] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DbIskhakov] SET RECOVERY BULK_LOGGED --модель восстоновлени€--
GO

ALTER DATABASE [DbIskhakov] SET  MULTI_USER 
GO

ALTER DATABASE [DbIskhakov] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DbIskhakov] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DbIskhakov] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DbIskhakov] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DbIskhakov] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DbIskhakov] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DbIskhakov] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DbIskhakov] SET  READ_WRITE 
GO


