SELECT COUNT (SUBJECT.SUBJECT)AS Количество_Предметов_На_Кафедре, PULPIT.PULPIT_NAME AS Имя_Кафедры
FROM SUBJECT
JOIN PULPIT ON SUBJECT.PULPIT = PULPIT.PULPIT
GROUP BY PULPIT_NAME
HAVING COUNT (SUBJECT.SUBJECT) <7
