CREATE PROCEDURE count_procedure
as
BEGIN
	SELECT COUNT(*) as [Количество процедур]
	FROM 
		( SELECT ROUTINE_NAME 
		  FROM master.INFORMATION_SCHEMA.ROUTINES
		  WHERE ROUTINE_TYPE = 'PROCEDURE' AND ROUTINE_NAME like 'sp_%'
		  UNION 
		  SELECT ROUTINE_NAME
		  FROM msdb.INFORMATION_SCHEMA.ROUTINES
		  WHERE ROUTINE_TYPE = 'PROCEDURE' AND ROUTINE_NAME like 'sp_%'
		) names;
END;